apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-server
  namespace: openstack
  labels:
    app: policy-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: policy-server
  template:
    metadata:
      labels:
        app: policy-server
    spec:
      containers:
      - name: policy-server
        image: ghcr.io/mehmettopcu/goslo.policy.server:main
        imagePullPolicy: Always
        command: ["/usr/local/bin/policy-server"]
        args: ["-policy-dir", "/policy-files", "-addr", ":8082", "-log-stdout", "true", "-watch-config", "false"]
        ports:
        - containerPort: 8082
          name: http
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        volumeMounts:
        - name: policy-config
          mountPath: /policy-files/nova.yaml
          subPath: nova.yaml
        - name: logs
          mountPath: /var/log/policy-server
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: policy-config
        configMap:
          name: policy-config
      - name: logs
        emptyDir: {} 