apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
- deployment.yaml
- service.yaml
- configmap.yaml

commonLabels:
  app: policy-server

images:
- name: policy-server
  newName: ghcr.io/mehmettopcu/goslo.policy.server
  newTag: main 