apiVersion: v1
kind: Service
metadata:
  name: policy-server
  namespace: openstack
  labels:
    app: policy-server
spec:
  type: ClusterIP
  ports:
  - port: 8082
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: policy-server 